# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[time]
disabled = false
format = "ğŸ•‘ $time($style) "
#format = 'ğŸ•™[\[ $time \]]($style) '
#time_format = "%T"
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"
#time_format = "%I:%M%P ï¸"

[cmd_duration]
min_time = 10_000                    # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[git_commit]
format = "[\\($hash$tag\\)]($style) "
only_detached = false

[golang]
symbol = "golang "
format = "| [$symbol($version )]($style)"

[nodejs]
symbol = "nodejs "
format = "| [$symbol($version )]($style)"
